In [18]:
import pandas as pd
import numpy as np

indexes=[1,2,3,4,5,6]
columns=['A','B','C','D']

df= pd.DataFrame(np.random.randint(0,100,size=(6,4)), columns=columns, index=indexes)
print(df)

    A   B   C   D
1   4  59  74  36
2  56  28  65  86
3   7  27  16  30
4  39  97   4  62
5  33  12  30  24
6  15   8  16  68


In [19]:
print(df.head(2))
print(df.tail(2))

    A   B   C   D
1   4  59  74  36
2  56  28  65  86
    A   B   C   D
5  33  12  30  24
6  15   8  16  68


In [20]:
print(df.values)
print('\n')
print(df.index)
print('\n')
print(df.columns)
print('\n')
print(df.describe)

[[ 4 59 74 36]
 [56 28 65 86]
 [ 7 27 16 30]
 [39 97  4 62]
 [33 12 30 24]
 [15  8 16 68]]


Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')


Index(['A', 'B', 'C', 'D'], dtype='object')


<bound method NDFrame.describe of     A   B   C   D
1   4  59  74  36
2  56  28  65  86
3   7  27  16  30
4  39  97   4  62
5  33  12  30  24
6  15   8  16  68>


In [23]:
df= df.sort_values(by=['B','C'] , ascending=[False, True])
print(df)

    A   B   C   D
4  39  97   4  62
1   4  59  74  36
2  56  28  65  86
3   7  27  16  30
5  33  12  30  24
6  15   8  16  68


In [26]:
S=pd.Series([1,2,3,4,5,6], index=indexes)
print(S)
print('\n')
df['F']=S
print(df)

1    1
2    2
3    3
4    4
5    5
6    6
dtype: int64


    A   B   C   D  F
4  39  97   4  62  4
1   4  59  74  36  1
2  56  28  65  86  2
3   7  27  16  30  3
5  33  12  30  24  5
6  15   8  16  68  6


In [38]:
df=df.astype(float)
df.at[3,'F']= np.nan
df.at[5,'F']= np.nan
print(df)
print('\n')
result = df.loc[[1,2,3], ['A', 'F']]
print(result)

      A     B     C     D    F
4  39.0  97.0   4.0  62.0  4.0
1   4.0  59.0  74.0  36.0  1.0
2  56.0  28.0  65.0  86.0  2.0
3   7.0  27.0  16.0  30.0  NaN
5  33.0  12.0  30.0  24.0  NaN
6  15.0   8.0  16.0  68.0  6.0


      A    F
1   4.0  1.0
2  56.0  2.0
3   7.0  NaN


In [40]:
df1= df.dropna()
print(df1)

      A     B     C     D    F
4  39.0  97.0   4.0  62.0  4.0
1   4.0  59.0  74.0  36.0  1.0
2  56.0  28.0  65.0  86.0  2.0
6  15.0   8.0  16.0  68.0  6.0


In [41]:
df2= df.fillna(df['F'].mean())
print(df2)

      A     B     C     D     F
4  39.0  97.0   4.0  62.0  4.00
1   4.0  59.0  74.0  36.0  1.00
2  56.0  28.0  65.0  86.0  2.00
3   7.0  27.0  16.0  30.0  3.25
5  33.0  12.0  30.0  24.0  3.25
6  15.0   8.0  16.0  68.0  6.00
